### ISSUE TITLE
Determine how to read Event Hub metadata on AZ Functions

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7#428]
We are trying to implement an Azure function in Kotlin (1.7.22, JVM 11) that can receive and read EventData metadata such as enqueuedtime and offset.

I’ve seen online examples of using the following signature for the function method:

``` kotlin
@FunctionName("myFunction")
fun eventHubProcessor(
        @EventHubTrigger(
            name = "event", 
            eventHubName = "%EventHubReceiveName%",
            consumerGroup = "%EventHubConsumerGroup%",
            connection = "EventHubConnectionString") 
            events: List<EventData>,
        context: ExecutionContext) {

``` 
That signature, where events is of type EventData (instead of String to receive only the event body alone), compiles fine, but  throws the following errors:

```
Executed 'Functions.receiverdebatcher001' (Failed, Id=0d1fc292-211b-4116-b95c-a1aa1447afae, Duration=4ms)
[2022-12-20T13:55:48.099Z] System.Private.CoreLib: Exception while executing function: Functions.receiverdebatcher001. System.Private.CoreLib: Result: Failure
Exception: ClassCastException: class sun.reflect.generics.reflectiveObjects.WildcardTypeImpl cannot be cast to class java.lang.Class (sun.reflect.generics.reflectiveObjects.WildcardTypeImpl and java.lang.Class are in module java.base of loader 'bootstrap')
Stack: java.lang.ClassCastException: class sun.reflect.generics.reflectiveObjects.WildcardTypeImpl cannot be cast to class java.lang.Class (sun.reflect.generics.reflectiveObjects.WildcardTypeImpl and java.lang.Class are in module java.base of loader 'bootstrap')
[2022-12-20T13:55:48.099Z]       at com.microsoft.azure.functions.worker.binding.DataOperations.apply(DataOperations.java:105)
[2022-12-20T13:55:48.099Z]       at com.microsoft.azure.functions.worker.binding.DataSource.computeByType(DataSource.java:56)
[2022-12-20T13:55:48.099Z]       at com.microsoft.azure.functions.worker.binding.RpcJsonDataSource.computeByType(RpcJsonDataSource.java:15)
[2022-12-20T13:55:48.099Z]       at com.microsoft.azure.functions.worker.binding.DataSource.computeByName(DataSource.java:42)
[2022-12-20T13:55:48.099Z]       at com.microsoft.azure.functions.worker.binding.RpcJsonDataSource.computeByName(RpcJsonDataSource.java:15)
[2022-12-20T13:55:48.099Z]       at com.microsoft.azure.functions.worker.binding.BindingDataStore.getDataByName(BindingDataStore.java:62)
[2022-12-20T13:55:48.099Z]       at com.microsoft.azure.functions.worker.broker.ParameterResolver.resolve(ParameterResolver.java:59)
[2022-12-20T13:55:48.099Z]       at com.microsoft.azure.functions.worker.broker.ParameterResolver.resolve(ParameterResolver.java:42)
[2022-12-20T13:55:48.099Z]       at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:53)
[2022-12-20T13:55:48.100Z]       at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:61)
[2022-12-20T13:55:48.100Z]       at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
[2022-12-20T13:55:48.100Z]       at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
[2022-12-20T13:55:48.100Z]       at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
[2022-12-20T13:55:48.100Z]       at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
[2022-12-20T13:55:48.100Z]       at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2022-12-20T13:55:48.100Z]       at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2022-12-20T13:55:48.100Z]       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2022-12-20T13:55:48.100Z]       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2022-12-20T13:55:48.100Z]       at java.base/java.lang.Thread.run(Thread.java:829)
[2022-12-20T13:55:48.100Z] .

```

**Comment by mscaldas2012** [comment]
Currently trying to open a support ticket with Microsoft

**Comment by mscaldas2012** [comment]
Opened a ticket with CDC Service Desk as instructed.
https://servicedesk.cdc.gov/sp?id=ticket&table=sc_req_item&sys_id=7d910d071b24e91c5adea8efe54bcb1d

**Comment by mscaldas2012** [comment]
Microsoft provided a solution to this problem by using a SystemProperties Pojo with @Binding Name

```
 @BindingName("SystemPropertiesArray")eventHubMD:List<EventHubMetadata>,
```
And the Pojo must be defined exactly like this (with capital uppercase properties:

```
data class EventHubMetadata(
    var SequenceNumber:Int,
    var Offset:Long,
    var PartitionKey:String?,
    var EnqueuedTimeUtc:String
)
```

**Comment by rmharrison** [comment]
@mscaldas2012 : Option...you're welcome to share with the community on stackoverflow
[This](https://stackoverflow.com/questions/60338607/how-to-set-systemproperties-on-an-eventhub-out-bindings-in-an-azure-function) post suggests one cannot, but you clearly can with the CamelCase.
